2025-05-15 16:45:23,169 INFO    MainThread:3910 [wandb_setup.py:_flush():70] Current SDK version is 0.19.11
2025-05-15 16:45:23,170 INFO    MainThread:3910 [wandb_setup.py:_flush():70] Configure stats pid to 3910
2025-05-15 16:45:23,170 INFO    MainThread:3910 [wandb_setup.py:_flush():70] Loading settings from /root/.config/wandb/settings
2025-05-15 16:45:23,170 INFO    MainThread:3910 [wandb_setup.py:_flush():70] Loading settings from /workspace/diffusion-llms/wandb/settings
2025-05-15 16:45:23,170 INFO    MainThread:3910 [wandb_setup.py:_flush():70] Loading settings from environment variables
2025-05-15 16:45:23,170 INFO    MainThread:3910 [wandb_init.py:setup_run_log_directory():724] Logging user logs to ./models/regressor_mlp/wandb/run-20250515_164523-myewwgon/logs/debug.log
2025-05-15 16:45:23,170 INFO    MainThread:3910 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to ./models/regressor_mlp/wandb/run-20250515_164523-myewwgon/logs/debug-internal.log
2025-05-15 16:45:23,170 INFO    MainThread:3910 [wandb_init.py:init():852] calling init triggers
2025-05-15 16:45:23,170 INFO    MainThread:3910 [wandb_init.py:init():857] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-05-15 16:45:23,170 INFO    MainThread:3910 [wandb_init.py:init():893] starting backend
2025-05-15 16:45:23,170 INFO    MainThread:3910 [wandb_init.py:init():897] sending inform_init request
2025-05-15 16:45:23,174 INFO    MainThread:3910 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-05-15 16:45:23,174 INFO    MainThread:3910 [wandb_init.py:init():907] backend started and connected
2025-05-15 16:45:23,175 INFO    MainThread:3910 [wandb_init.py:init():1005] updated telemetry
2025-05-15 16:45:23,179 INFO    MainThread:3910 [wandb_init.py:init():1029] communicating run to backend with 90.0 second timeout
2025-05-15 16:45:23,964 INFO    MainThread:3910 [wandb_init.py:init():1104] starting run threads in backend
2025-05-15 16:45:24,072 INFO    MainThread:3910 [wandb_run.py:_console_start():2573] atexit reg
2025-05-15 16:45:24,073 INFO    MainThread:3910 [wandb_run.py:_redirect():2421] redirect: wrap_raw
2025-05-15 16:45:24,073 INFO    MainThread:3910 [wandb_run.py:_redirect():2490] Wrapping output streams.
2025-05-15 16:45:24,073 INFO    MainThread:3910 [wandb_run.py:_redirect():2513] Redirects installed.
2025-05-15 16:45:24,074 INFO    MainThread:3910 [wandb_init.py:init():1150] run started, returning control to user process
2025-05-15 16:45:28,340 INFO    MainThread:3910 [wandb_run.py:_config_callback():1436] config_cb None None {'model_type': 'regressor', 'hidden_size': 4096, 'context_length': 1024, 'cache_dir': '/root/cache_hidden', 'learning_rate': 0.001, 'pos_weight': 0.277}
2025-05-15 16:47:16,078 INFO    MsgRouterThr:3910 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-05-15 16:47:17,245 ERROR   MainThread:3910 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-15 16:47:17,246 ERROR   MainThread:3910 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
